---
- name: Install Software
  hosts: all
  tasks:
    - name: Install Software {{ item }}
      win_chocolatey:
        name: {{ item }}
        state: present
        log_path: c:\ansible_choco.txt
      loop:
        - jre8
        - notepadplusplus
        - firefoxesr
      