---
# tasks file for base
- name: Installing software using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ software }}"
    state: present
    version: latest
    allow_empty_checksums: yes
    allow_multiple: yes
    force: yes
    validate_certs: no
