ansible_port: 5986
ansible_connection: winrm
ansible_winrm_transport: credssp
ansible_winrm_server_cert_validation: ignore
ansible_winrm_scheme: https
ansible_winrm_message_encryption: auto
ansible_winrm_send_cbt: false